'use strict';
document.documentElement.classList.add('has-js');
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);menu.querySelector('span').textContent=open?'−':'＋';});
nav?.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.click();menu.focus();}});
const tabs=Array.from(document.querySelectorAll('[data-tab]'));
function selectTab(tab,focus=false){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!selected;});if(focus)tab.focus();}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();selectTab(tabs[next],true);}});});
const filters=Array.from(document.querySelectorAll('[data-filter]')),search=document.querySelector('.roster-search input'),sections=Array.from(document.querySelectorAll('[data-team]'));let active='all';
function filterRoster(){let matches=0;const term=(search?.value||'').trim().toLowerCase();sections.forEach(section=>{let count=0;section.querySelectorAll('.member-grid li').forEach(member=>{const show=member.textContent.toLowerCase().includes(term);member.hidden=!show;if(show)count++;});section.querySelectorAll('.roster-group-label').forEach(label=>{const list=label.nextElementSibling;label.hidden=!Array.from(list.children).some(member=>!member.hidden);});section.hidden=!(active==='all'||active===section.dataset.team)||count===0;if(!section.hidden)matches+=count;});const status=document.querySelector('.filter-status');if(status)status.textContent=matches?`${matches} subteam member${matches===1?'':'s'}${term?' matching your search':''}`:'No members found. Try another name or team.';}
filters.forEach(button=>button.addEventListener('click',()=>{active=button.dataset.filter;filters.forEach(b=>{const on=b===button;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});filterRoster();}));search?.addEventListener('input',filterRoster);if(sections.length)filterRoster();
function hashTeam(){if(!location.hash.startsWith('#team-'))return;active='all';if(search)search.value='';filters.forEach(b=>{const on=b.dataset.filter==='all';b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});filterRoster();document.getElementById(location.hash.slice(1))?.scrollIntoView({block:'start'});}
if(sections.length){hashTeam();window.addEventListener('hashchange',hashTeam);}
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}});},{threshold:.08});document.querySelectorAll('.home-intro,.team-explorer,.pathways>a,.member-captains,.award-grid>div,.impact-cards article,.content-section').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el);});}
// The existing API fills the gallery asynchronously; progressively enhance each real photo.
const gallery=document.querySelector('.photo-collage');
if(gallery){const dialog=document.createElement('dialog');dialog.className='photo-dialog';dialog.setAttribute('aria-label','Community photo');const close=document.createElement('button');close.type='button';close.textContent='Close ×';const image=document.createElement('img'),caption=document.createElement('p');dialog.append(close,image,caption);document.body.append(dialog);close.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});const enhance=()=>{gallery.querySelectorAll('figure').forEach(figure=>{const img=figure.querySelector('img');if(!img||figure.querySelector('button'))return;const button=document.createElement('button');button.type='button';button.setAttribute('aria-label','Enlarge '+img.alt);img.replaceWith(button);button.append(img);button.addEventListener('click',()=>{image.src=img.src;image.alt=img.alt;caption.textContent=figure.querySelector('figcaption')?.textContent||'';dialog.showModal();});});};new MutationObserver(enhance).observe(gallery,{childList:true,subtree:true});enhance();}
